services:
  tutorialapp:
    image: mcr.microsoft.com/dotnet/sdk:9.0
    working_dir: /app/aspnetcoreapp
    ports:
      - "5070:5070"
    volumes:
      - ./:/app
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:5070
    command: dotnet run --urls "http://0.0.0.0:5070"
