services:
  todoapi:
    image: mcr.microsoft.com/dotnet/sdk:9.0
    container_name: todoapi
    working_dir: /app/TodoApi
    volumes:
      - ./:/app
    ports:
      - "5080:5080"
    command: >
      sh -c "dotnet restore &&
      echo 'Adding Microsoft Entity Framework Package...';
      dotnet add package Microsoft.EntityFrameworkCore --version 9.0.1 &&
      echo 'Publishing for smaller image...';
      dotnet publish -c Release && 
      echo 'Running the api...';
      dotnet run --urls http://0.0.0.0:5080"
